---
esphome:
  name: test-nuki

  libraries:
    - Preferences
    - https://github.com/h2zero/NimBLE-Arduino#1.4.0
    - Crc16
    - https://github.com/I-Connect/NukiBleEsp32

esp32:
  framework:
    type: arduino
    version: 2.0.16
    platform_version: 6.7.0

packages:
  common: !include shared-config.yaml
