esphome:
  name: test-nuki

wifi:
  ssid: "My Network"
  password: "My Password"

api:

logger:
  logs:
    component: ERROR

external_components:
  - source:
      type: local
      path: "../components/"

lock:
  - platform: nuki_lock
    name: Nuki Lock

    is_connected:
      name: "Nuki Connected"
    is_paired:
      name: "Nuki Paired"
    battery_critical:
      name: "Nuki Battery Critical"
    door_sensor:
      name: "Nuki Door Sensor"

    battery_level:
      name: "Nuki Battery Level"
    bt_signal_strength:
      name: "Bluetooth Signal Strength"
    
    door_sensor_state:
      name: "Nuki Door Sensor: State"
    last_unlock_user:
      name: "Nuki Last Unlock User"
    last_lock_action:
      name: "Nuki Last Lock Action"
    last_lock_action_trigger:
      name: "Nuki Last Lock Action Trigger"
    pin_status:
      name: "Nuki Security Pin Status"

    unpair:
      name: "Nuki Unpair Device"
      
    pairing_mode:
      name: "Nuki Pairing Mode"
    auto_unlatch:
      name: "Nuki Auto unlatch"
    button_enabled:
      name: "Nuki Button: Locking operations"
    led_enabled:
      name: "Nuki LED Signal"
    night_mode_enabled:
      name: "Nuki Night Mode"
    night_mode_auto_lock_enabled:
      name: "Nuki Night Mode: Auto Lock"
    night_mode_auto_unlock_disabled:
      name: "Nuki Night Mode: Reject Auto Unlock"
    night_mode_immediate_lock_on_start_enabled:
      name: "Nuki Night Mode: Lock at Start Time"
    auto_lock_enabled:
      name: "Nuki Auto Lock"
    auto_unlock_disabled:
      name: "Nuki Auto Unlock: Disable"
    immediate_auto_lock_enabled:
      name: "Nuki Auto Lock: Immediately"
    auto_update_enabled:
      name: "Nuki Automatic Updates"
    single_lock_enabled:
      name: "Nuki Single Lock"
    dst_mode_enabled:
      name: "Nuki Daylight Saving Time"
    auto_battery_type_detection_enabled:
      name: "Nuki Automatic Battery Type Detection"

    led_brightness:
      name: "Nuki LED Brightness"
    timezone_offset:
      name: "Nuki Timezone: Offset"
    lock_n_go_timeout:
      name: "Nuki LockNGo Timeout"

    single_buton_press_action:
      name: "Nuki Single Button Press Action"
    double_buton_press_action:
      name: "Nuki Double Button Press Action"
    fob_action_1:
      name: "Nuki Fob Action 1"
    fob_action_2:
      name: "Nuki Fob Action 2"
    fob_action_3:
      name: "Nuki Fob Action 3"
    timezone:
      name: "Nuki Timezone"
    advertising_mode:
      name: "Nuki Advertising Mode"
    battery_type:
      name: "Nuki Battery Type"

    pairing_mode_timeout: 300s
    event: "nuki"
    security_pin: 1234
    alternative_connect_mode: true
    pairing_as_app: false
    query_interval_config: 3600s
    query_interval_auth_data: 7200s

    on_pairing_mode_on_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned on");
    on_pairing_mode_off_action:
      - lambda: ESP_LOGI("nuki_lock", "Pairing mode turned off");
    on_paired_action:
      - lambda: ESP_LOGI("nuki_lock", "Paired sucessfuly");

button:
  - platform: template
    name: Unpair
    on_press:
      - nuki_lock.unpair:

  - platform: template
    name: Enable pairing-mode
    on_press:
      - nuki_lock.set_pairing_mode:
          pairing_mode: true

  - platform: template
    name: Override security pin
    on_press:
      - nuki_lock.set_security_pin:
          security_pin: 1234