name: Nightly Firmware Build Check
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Nightly
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - file: .github/arduino-component.yaml
          - file: .github/idf-component.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Compile Firmware
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: ${{ matrix.config.file }}
          version: dev